config/routes.rb
Sigma::Application.routes.draw do
  get "contact/company"
  post "contact/send_to_sigma"

  get "contact/client"
  resources :employees

  get "welcome/index"

  get "client_balances/balance"
  get "client_balances/all_balances"

  match 'about_us' => 'welcome#about_us'
  match 'services' => 'welcome#services'
  match 'clients/:id' => 'clients#show'
  match 'clients/:id/points' => 'clients#points', as: 'client_points'
  match 'clients/by_cpf/:cpf/balances' => 'client_balances#all_balances'
  match 'clients/by_cpf/:cpf/promotions/:promotion_id/balance' => 'client_balances#balance'

  resources :points do
    collection do
      get '/report'
    end
  end

  resources :promotions

  devise_for :users

  resources :companies do
    resources :employees
  end

  resources :exchanges do
    collection do
      get '/report'
    end
  end

  root :to => 'welcome#index'

end

app/models/point.rb
# Represents one "transation".
# When the +Client+ buy something of +Company+,
# some amount of points is created.
# After create, the +ClientBalance+ it updated,
# through the +PointObserver+
class Point < ActiveRecord::Base
  belongs_to :client
  belongs_to :promotion
  belongs_to :company
  attr_accessible :value, :cpf, :promotion_id, :company_id
  validate :check_client_cpf

  # Callback to calculate points
  before_save :calculate_points

  # Fetches points by promotions
  scope :by_promotions, lambda {|promotions| {
    :include => :promotion, :conditions => { :promotion_id => promotions }
  }}

  scope :by_valid_promotions,
    lambda {  { :include => :promotion, :conditions => ['promotions.ending_date >= ?', Date.today] } }

  # Exchanges are negative points
  scope :exchanges, where('points.points < 0')

  scope :credits, where('points.points > 0')

  # Represents the client document
  attr_reader :cpf

  # Find or create a new client based on CPF,
  # then assign it to this point
  def cpf=(client_cpf)
    @cpf = client_cpf
    client = Client.find_or_create_by_cpf(client_cpf)
    self.client = client
  end

  # Group and count the points by date of creation
  def self.total_daily(start = Date.today.beginning_of_month, ending = Date.today.end_of_month)
    joins(:promotion).
      where(created_at: start.beginning_of_day..ending.end_of_day).
      group("date(points.created_at)").
      select('date(points.created_at) as day,
              count(*) as clients_count,
              sum(points.points) as total')
  end

  private

  # Use the Brazilian Rails to check CPF
  def check_client_cpf
    if not Cpf.new(@cpf).valido?
      errors.add :cpf, I18n.t('errors.messages.cpf_is_not_valid')
    end
  end

  # Calls +PointCalculator+ to solve the amount of points
  def calculate_points
    unless self.points
      self.points = PointCalculator.new(self.value, self.promotion).points
    end
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  load_and_authorize_resource
  before_filter :load_company

  # GET /points
  # GET /points.json
  def index
    @points = Point.by_promotions(@company.promotions)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @points }
    end
  end

  # GET /points/1
  # GET /points/1.json
  def show
    @point = Point.find(params[:id])

    @temp_password = @point.client.try(:user).try(:temporary_password)
    @balance = ClientBalance.find_by_client_id_and_promotion_id(@point.client_id, @point.promotion_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @point }
    end
  end

  # GET /points/new
  # GET /points/new.json
  def new
    @point = Point.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @point }
    end
  end

  # GET /points/1/edit
  def edit
    @point = Point.find(params[:id])
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(params[:point])
    @point.company = @company
    respond_to do |format|
      if @point.save
        @balance = ClientBalance.find_by_promotion_id_and_client_id(@point.promotion, @point.client)
        format.js 
        format.html { redirect_to @point, notice: t('sigma.points.successfully_created') }
        format.json { render json: @point, status: :created, location: @point }
      else
        format.html { render action: "new" }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /points/1
  # PUT /points/1.json
  def update
    @point = Point.find(params[:id])

    respond_to do |format|
      if @point.update_attributes(params[:point])
        format.html { redirect_to @point, notice: t('sigma.points.successfully_updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    respond_to do |format|
      format.html { redirect_to points_url }
      format.json { head :no_content }
    end
  end

  # GET /points/report
  def report
    begin
      @start, @ending = params[:graph_start].to_date, params[:graph_ending].to_date
    rescue
      @start, @ending = Date.yesterday, Date.today
    end

    @promotion = Promotion.find(params[:graph][:promotion_id])
    @company = @promotion.company
    @points_report = Point.credits.by_promotions(@promotion).
      total_daily(@start,@ending)

    respond_to do |format|
      format.html
    end
  end

  private

  def load_company
    @company ||= current_employee.company
  end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_client_info.html.erb
<div>
  <strong><%= ClientBalance.human_attribute_name('balance') %></strong>:
  <span id="client_balance"></span>
</div>
<div class="promotion-details">
  <strong class="promotion-details"><%= Promotion.human_attribute_name("points_to_exchange") %></strong>:
  <span class="promotion-details" id="promotion_points"></span>
</div>
<div class="exchange-box">
  <div class="alert alert-success">
  <%= t('sigma.infos.ready_to_exchange') %> 
  </div>
  <%= render :partial => 'exchange_form' %>
</div>

app/views/points/_exchange_form.html.erb
<%= form_tag('/exchanges') do %>
  <%= hidden_field_tag :exchange_client_cpf %>
  <%= hidden_field_tag :exchange_promotion_id %>
  <%= submit_tag(t('sigma.buttons.exchange'),:class => 'btn btn-primary', :id => 'exchange-button', data: { confirm: t('sigma.dialogs.are_you_sure') }) %>
<% end %>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.messages.not_saved', :resource => t('sigma.points.title'), :count => @point.errors.count) %></h2>
      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cpf, "CPF" %>
    <%= f.text_field :cpf, :maxlength => 11 %>
  </div>
  
  <div class="field">
    <%= f.label :promotion_id, Promotion.model_name.human %>
    <%= f.collection_select(:promotion_id, @company.promotions, :id, :name, :prompt => false) %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.number_field :value %>
  </div>
  
  <div class="actions">
    <%= f.submit t('.assign') %> 
  </div>
<% end %>

app/views/points/create.js.erb
$(document).ready(function () {
	<% if @balance.ready_to_exchange? %>
		/*
			ready_to_exchange para exibir o botão
		*/
	<% end %>
});

													

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @point %> |
<%= link_to 'Voltar', points_path %>

app/views/points/index.html.erb
<h2><%= t('sigma.reports.points.title') %></h2>
<%= render partial: '/reports/basic_promotions_form', locals: { :form_path => report_points_path } %>
<%= link_to t('sigma.buttons.back'), new_point_path %>

app/views/points/new.html.erb
<h2><%= t('.title') %></h2>

<div id="points-new-box">
  <%= render 'form' %>
</div>
<div id="client-info-box">
  <%= render 'client_info' %>
</div>

app/views/points/report.html.erb
<%= content_tag(:h2, t('sigma.reports.points.title')) %>

<%= content_tag(:h3, @promotion.name) %>

<%= link_to t('sigma.buttons.back'), :back %>

<p>
  <%= t('sigma.reports.points.promotion_description', :name => @promotion.name) %>
</p>

<%= content_tag(:div,'',:id => 'graphs', data: { exchanges: @points_report }) %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('datetime.prompts.day') %> </th>
      <th><%= t('.total_of_clients') %></th>
      <th><%= t('.total_of_points') %></th>
    </tr>
  </thead>
  <tbody>
    <% @points_report.each do |daily_points| %>
      <tr>
        <td> <%= l(daily_points.day.to_date) %> </td>
        <td> <%= daily_points.clients_count %> </td>
        <td> <%= daily_points.total %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('sigma.buttons.back'), :back %>

app/views/points/show.html.erb
<h2><%= t('.title') %></h2>

<p>
<b><%= t('.client_name') %>:</b>
<%= @point.client.try(:name) %>
</p>

<p>
<b><%= Client.human_attribute_name('cpf') %>:</b>
<%= @point.client.cpf %>
</p>

<% if @temp_password %>
  <p>
  <b><%= t('.temporary_password') %></b>:
  <%= @temp_password %>
  <span class="alert alert-info">
    <%= t('.temporary_password_hint') %>
  </span>
  </p>
<% end %>

<p>
<b><%= t('points.other') %>:</b>
<%= @point.points %>
</p>

<p>
  <b><%= t('.new_balance') %></b>:
  <%= @balance.balance %> / <%= @point.promotion.points_to_exchange %>
</p>

<p>
<b><%= Promotion.model_name.human %></b>:
<%= @point.promotion %>
</p>
<%= link_to t('sigma.buttons.back'), new_point_path, class: 'btn' %>