config/routes.rb
Sigma::Application.routes.draw do
  get "contact/company"
  post "contact/send_to_sigma"

  get "contact/client"
  resources :employees

  get "welcome/index"

  get "client_balances/balance"
  get "client_balances/all_balances"

  match 'about_us' => 'welcome#about_us'
  match 'services' => 'welcome#services'
  match 'clients/:id' => 'clients#show'
  match 'clients/:id/points' => 'clients#points', as: 'client_points'
  match 'clients/by_cpf/:cpf/balances' => 'client_balances#all_balances'
  match 'clients/by_cpf/:cpf/promotions/:promotion_id/balance' => 'client_balances#balance'

  resources :points do
    collection do
      get '/report'
    end
  end

  resources :promotions

  devise_for :users

  resources :companies do
    resources :employees
  end

  resources :exchanges do
    collection do
      get '/report'
    end
  end

  root :to => 'welcome#index'

end

app/models/employee.rb
# A +Company+ employee
#
# It can have two user roles:
#   - Admin: can create promotions and see the reports;
#   - Cashier: can create points and see client balances.
class Employee < ActiveRecord::Base
  belongs_to :company
  belongs_to :user
  attr_accessible :name, :company, :user, :user_attributes
  accepts_nested_attributes_for :user

  delegate :name, to: :user, :allow_nil => true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource

  before_filter :load_company
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.where(company_id: params[:company_id]).includes(:user)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])
    @roles = Role.where(name: ['cashier','admin'])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new
    @employee.build_user
    @roles = Role.where(name: ['cashier','admin'])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
    @roles = Role.where(name: ['cashier','admin'])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])
    @employee.company = @company
    @roles = Role.where(name: ['cashier','admin'])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to [@company, @employee], notice: t('employees.messages.successfully_created') }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    @roles = Role.where(name: ['cashier','admin'])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to [@company,@employee], notice: t('employees.messages.successfully_updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to company_employees_path(@company) }
      format.json { head :no_content }
    end
  end

  private
  def load_company
    @company ||= Company.find(params[:company_id])
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for([@company, @employee]) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('employees.errors.explanation') %></h2>
      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :user do |user| %>
    <%= render 'users_form', f: user, roles: @roles %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/_users_form.html.erb
<p>
<%= f.label :username %>
<%= f.text_field :username %>
</p>

<p>
<%= f.label :role_id %>
<%= f.collection_select(:role_id, @roles, :id, :human_name, :prompt => false) %>
</p>

<p>
<%= f.label :name %>
<%= f.text_field :name %>
</p>

<p>
<%= f.label :email %>
<%= f.email_field :email %>
</p>

<p>
<%= f.label :password %>
<%= f.password_field :password %>
</p>

<p>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</p>

app/views/employees/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

<%= link_to t('sigma.buttons.show'), @employee %> |
<%= link_to t('sigma.buttons.back'), company_employees_path(@company) %>

app/views/employees/index.html.erb
<h2><%= t('.title') %></h2>

<table class="table">
  <tr>
    <th><%= User.human_attribute_name(:name) %></th>
    <th><%= Role.model_name.human %></th>
    <th><%= User.human_attribute_name(:login) %></th>
    <th><%= User.human_attribute_name(:email) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.user.name %></td>
    <td><%= employee.user.role.human_name %></td>
    <td><%= employee.user.username %></td>
    <td><%= employee.user.email %></td>
    <td><%= link_to t('sigma.buttons.show'), [employee.company, employee], class: 'btn btn-primary' %></td>
    <td><%= link_to t('sigma.buttons.edit'), edit_company_employee_path(employee.company, employee), class: 'btn' %></td>
    <td><%= link_to t('sigma.buttons.destroy'), [@company,employee], method: :delete, data: { confirm: t('sigma.dialogs.are_you_sure') }, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('.new'), new_company_employee_path(@company), class: 'btn' %>

app/views/employees/new.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

<%= link_to t('sigma.buttons.back'), company_employees_path(@company) %>

app/views/employees/show.html.erb
<p>
<strong><%= User.human_attribute_name("name") %></strong>:
<%= @employee.name %>
</p>

<p>
<strong><%= User.human_attribute_name("username") %></strong>:
<%= @employee.user.username %>
</p>

<p>
<strong><%= User.human_attribute_name("email") %></strong>:
<%= @employee.user.email %>
</p>

<p>
<strong><%= Role.model_name.human %></strong>:
<%= @employee.user.role.human_name %>
</p>

<%= link_to t('sigma.buttons.edit'), edit_company_employee_path(@company,@employee) %> |
<%= link_to t('sigma.buttons.back'), company_employees_path(@company) %>