config/routes.rb
Sigma::Application.routes.draw do
  get "contact/company"
  post "contact/send_to_sigma"

  get "contact/client"
  resources :employees

  get "welcome/index"

  get "client_balances/balance"
  get "client_balances/all_balances"

  match 'about_us' => 'welcome#about_us'
  match 'services' => 'welcome#services'
  match 'clients/:id' => 'clients#show'
  match 'clients/:id/points' => 'clients#points', as: 'client_points'
  match 'clients/by_cpf/:cpf/balances' => 'client_balances#all_balances'
  match 'clients/by_cpf/:cpf/promotions/:promotion_id/balance' => 'client_balances#balance'

  resources :points do
    collection do
      get '/report'
    end
  end

  resources :promotions

  devise_for :users

  resources :companies do
    resources :employees
  end

  resources :exchanges do
    collection do
      get '/report'
    end
  end

  root :to => 'welcome#index'

end

app/models/company.rb
# The +Company+ can be of any kind.
# It will be visible to clients.
# The "root" User is the only one
# who can create Companies
class Company < ActiveRecord::Base
  attr_accessible :cnpj, :email, :name, :phone, :website, :image

  validates :name, :presence => true
  has_many :promotions

  # Validation of e-mail with regex
  validates :email, :presence => true, :format => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  # Validation of CNPJ using brazilian rails
  validates :cnpj, :presence => true, :cnpj => true

  has_attached_file :image,
    :path => ":rails_root/public/system/companies/:attachment/:id/:style/:filename",
    :url => "/system/companies/:attachment/:id/:style/:filename",
    :styles => { :medium => "300x300>", :thumb => "100x100>" }

  # The +String+ representation of campany
  def to_s
    self.name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: t( "sigma.companies_message.successfully_created" ) }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: t( "sigma.companies_message.successfully_updated" ) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.messages.not_saved', :count => @company.errors.count, :resource => @company.class.model_name.human) %></h2>
      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cnpj %>
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1><%= t('sigma.buttons.edit_profile') %></h1>

<%= render 'form' %>

<%= link_to t('sigma.buttons.show'), @company %> |
<%= link_to t('sigma.buttons.back'), companies_path %>

app/views/companies/index.html.erb
<h1><%= Company.model_name.human.pluralize %></h1>

<table class="table">
  <tr>
    <th><%= Company.human_attribute_name("name") %></th>
    <th><%= Company.human_attribute_name("cnpj") %></th>
    <th><%= Company.human_attribute_name("phone") %></th>
    <th><%= Company.human_attribute_name("website") %></th>
    <th><%= Company.human_attribute_name("email") %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= link_to company.name, company %></td>
    <td><%= company.cnpj %></td>
    <td><%= company.phone %></td>
    <td><%= company.website %></td>
    <td><%= company.email %></td>
    <td><%= link_to t('.employees'), company_employees_path(company), class: 'btn btn-primary' %></td>
    <td><%= link_to t('sigma.buttons.edit'), edit_company_path(company), class: 'btn' %></td>
    <td><%= link_to t('sigma.buttons.destroy'), company, method: :delete,
      data: { confirm: t('sigma.dialogs.are_you_sure') }, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to "#{t('sigma.buttons.create')} #{Company.model_name.human}", new_company_path %>

app/views/companies/new.html.erb
<h1><%= "#{t('sigma.buttons.create')} #{Company.model_name.human}" %></h1>

<%= render 'form' %>

<%= link_to t('sigma.buttons.back'), companies_path %>

app/views/companies/show.html.erb
<p>
  <%= image_tag(@company.image.url) %>
</p>
<p>
<b><%= Company.human_attribute_name("name") %>:</b>
  <%= @company.name %>
</p>

<p>
<b><%= Company.human_attribute_name("cnpj") %>:</b>
  <%= @company.cnpj %>
</p>

<p>
<b><%= Company.human_attribute_name("phone") %>:</b>
  <%= @company.phone %>
</p>

<p>
<b><%= Company.human_attribute_name("website") %>:</b>
  <%= @company.website %>
</p>

<p>
<b><%= Company.human_attribute_name("email") %>:</b>
  <%= @company.email %>
</p>

<%= link_to t('companies.index.employees'), company_employees_path(@company), class: 'btn' %> |
<%= link_to t('sigma.buttons.edit'), edit_company_path(@company), class: 'btn' %> |
<%= link_to t('sigma.buttons.back'), companies_path, class: 'btn' %>