config/routes.rb
Sigma::Application.routes.draw do
  get "contact/company"
  post "contact/send_to_sigma"

  get "contact/client"
  resources :employees

  get "welcome/index"

  get "client_balances/balance"
  get "client_balances/all_balances"

  match 'about_us' => 'welcome#about_us'
  match 'services' => 'welcome#services'
  match 'clients/:id' => 'clients#show'
  match 'clients/:id/points' => 'clients#points', as: 'client_points'
  match 'clients/by_cpf/:cpf/balances' => 'client_balances#all_balances'
  match 'clients/by_cpf/:cpf/promotions/:promotion_id/balance' => 'client_balances#balance'

  resources :points do
    collection do
      get '/report'
    end
  end

  resources :promotions

  devise_for :users

  resources :companies do
    resources :employees
  end

  resources :exchanges do
    collection do
      get '/report'
    end
  end

  root :to => 'welcome#index'

end

app/models/promotion.rb
# The +Company+ +Promotion+
# It could be by value or by points
# "By points" promotions is the type of promotion
# that gives points based on some "constant" points.
# The opposite is "by value" promotions
# which is the promotion that gives points based
# on the poins by value.
#
# Example:
#   I have a Promotion that is by value.
#   For $10, it gives me 1 point.
#   I buy $100 and this promotion gives me 100 points.
class Promotion < ActiveRecord::Base
  belongs_to :company
  belongs_to :user
  belongs_to :promotion_category
  attr_accessible :image, :ending_date, :initial_date, :name, :points, :value, :description, :promotion_category_id, :points_to_exchange
  has_attached_file :image,
    :styles => { :medium => "300x300>", :thumb => "100x100>", :list => "60x60>" }
  
  validates :name, :presence => true
  validates :description, :presence => true

  # Scope promotions by company
  scope :by_company, lambda{|company| where(company_id: company) }

  # Set default point value
  before_save :set_default_point_value
  
  # The +String+ representation of points
  def to_s
    self.name
  end

  # Returns if promotions is by points
  def by_points?
    self.promotion_category.present? and self.promotion_category.name == "points"
  end

  private

  def set_default_point_value
    self.points = 1 unless self.points.present?
  end

end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  load_and_authorize_resource
  before_filter :load_company

  # GET /promotions
  # GET /promotions.json
  def index
    @promotions = Promotion.by_company(@company)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @promotions }
    end
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
    @promotion = Promotion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @promotion }
    end
  end

  # GET /promotions/new
  # GET /promotions/new.json
  def new
    @promotion = Promotion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promotion }
    end
  end

  # GET /promotions/1/edit
  def edit
    @promotion = Promotion.find(params[:id])
  end

  # POST /promotions
  # POST /promotions.json
  def create
    @promotion = Promotion.new(params[:promotion])
    @promotion.company = @company
    @promotion.user = current_user

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to @promotion, notice: t('sigma.promotions.successfully_created') }
        format.json { render json: @promotion, status: :created, location: @promotion }
      else
        format.html { render action: "new" }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promotions/1
  # PUT /promotions/1.json
  def update
    @promotion = Promotion.find(params[:id])

    respond_to do |format|
      if @promotion.update_attributes(params[:promotion])
        format.html { redirect_to @promotion, notice: t('sigma.promotions.successfully_updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion = Promotion.find(params[:id])
    @promotion.destroy

    respond_to do |format|
      format.html { redirect_to promotions_url }
      format.json { head :no_content }
    end
  end

  private

  def load_company
    @company = current_user.employee.company
  end
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_form.html.erb
<%= form_for(@promotion) do |f| %>
  <% if @promotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.messages.not_saved', :count => @promotion.errors.count, :resource => @promotion.class.model_name.human) %></h2>
      <ul>
      <% @promotion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="name" class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div id="initial_date" class="field">
    <%= f.label :initial_date %>
    <%= f.date_select :initial_date %>
  </div>
  <div id="ending_date" class="field">
    <%= f.label :ending_date %>
    <%= f.date_select :ending_date, :default => 60.days.from_now %>
  </div>

  <div id="promotion_category" id="selecao">
    <div class="alert alert-info">
      <strong>Promoção por pontos:</strong> A cada nova compra, o cliente ganhará determinada quantidade
      de pontos, independente do valor da compra. <br />
      <strong>Promoção por valor:</strong> A cada nova compra, a pontuação será calculada com base no
      total gasto pelo cliente. Este é o modelo mais indicado.
    </div>
    <label>
      <%= f.radio_button(:promotion_category_id, PromotionCategory.by_points.id, :checked => true) %>
      <%= t('promotions.form.points') %>
    </label>
    <label>
      <%= f.radio_button(:promotion_category_id, PromotionCategory.by_value.id) %>
      <%= t('promotions.form.value') %>
    </label>
  </div>

  <div id="points" class="field">
    <%= f.label :points %>
    <%= f.number_field :points %>
  </div>
  <div id="value" class="field hidden">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <div class="alert alert-info">
      <%= t('promotions.points_to_exchange') %>
    </div>
    <%= f.label :points_to_exchange %>
    <%= f.number_field :points_to_exchange %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promotions/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

<%= link_to t('sigma.buttons.show'), @promotion %> |
<%= link_to t('sigma.buttons.back'), promotions_path %>

app/views/promotions/index.html.erb
<h1><%= t('sigma.promotions.title') %></h1>

<p>
<%= link_to t('sigma.promotions.new'), new_promotion_path, class: 'btn' %>
</p>

<table class="table">
  <tr>
    <th><%= Promotion.human_attribute_name('name') %></th>
    <th><%= Promotion.human_attribute_name('initial_date') %></th>
    <th><%= Promotion.human_attribute_name('ending_date') %></th>
    <th><%= Promotion.human_attribute_name('points') %></th>
    <th><%= Promotion.human_attribute_name('value') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @promotions.each do |promotion| %>
  <tr>
    <td><%= link_to promotion.name, promotion %></td>
    <td><%= l(promotion.initial_date) %></td>
    <td><%= l(promotion.ending_date) %></td>
    <td><%= promotion.points %></td>
    <td><%= promotion.value %></td>
    <td><%= link_to t('sigma.buttons.show'), promotion, class: 'btn btn-primary' %></td>

    <% if can? :update, promotion %>
      <td>
        <%= link_to t('sigma.buttons.edit'), edit_promotion_path(promotion), class: 'btn' %>
      </td>
      <td>
        <%= link_to t('sigma.buttons.destroy'), promotion, method: :delete, data: { confirm: t('sigma.dialogs.are_you_sure') }, class: 'btn btn-danger' %>
      </td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

app/views/promotions/new.html.erb
<h2><%= t('sigma.promotions.new') %></h2>
<%= render 'form' %>

<%= link_to t('sigma.buttons.back'), promotions_path %>

app/views/promotions/show.html.erb
<p>
  <%= image_tag @promotion.image.url %>
</p>

<p>
  <b><%= Promotion.human_attribute_name('name') %>:</b>
  <%= @promotion.name %>
</p>

<p>
  <b><%= Promotion.human_attribute_name('initial_date') %>:</b>
  <%= @promotion.initial_date %>
</p>

<p>
  <b><%= Promotion.human_attribute_name('ending_date') %>:</b>
  <%= @promotion.ending_date %>
</p>

<p>
  <b><%= Promotion.human_attribute_name('points') %>:</b>
  <%= @promotion.points %>
</p>

<p>
  <b><%= Promotion.human_attribute_name('value') %>:</b>
  <%= @promotion.value %>
</p>

<p>
  <b><%= Company.model_name.human %>:</b>
  <%= @promotion.company %>
</p>


<%= link_to t('sigma.buttons.edit'), edit_promotion_path(@promotion) %> |
<%= link_to t('sigma.buttons.back'), promotions_path %>